### ISSUE TITLE
Supports on R-CAR V3M/H3 series ?

### ISSUE THREAD

**Issue by jasonakon** [renesas-rz/meta-renesas-ai#2]
May i ask, does this meta-layers support Renesas R-CAR V3M/H3 families ? Recently i have struggled to get tensorflow working on these platforms.

**Comment by patersonc** [comment]
Hello @jasonakon, thanks for getting in touch.

Currently this project is only for the Renesas RZ/G1 series of SoCs. However support will be added for RZ/G2 in the next couple of months. Once this work is done it shouldn't be too much of a task to port over to R-Car Gen3.

Let me know if there is anything else I can help you with.

Regards, Chris

**Comment by jasonakon** [comment]
Hi @patersonc , was wondering are you from Renesas ? 
Because i'm one of the the developers on the Renesas R-CAR GEN3 which struggling in setting-up tf & tflite environment. 

Hopefully, if you could give me some hints on the compatible "local.conf and bblayers.conf" on the rcar gen3 platform. Thank you !

**Comment by patersonc** [comment]
Yep. Drop me a line internally.

We hope to release support for RZ/G2 in the next couple of weeks.

**Comment by patersonc** [comment]
Hello @jasonakon,

Did you manage to make any progress with building for R-Car Gen3 in the end?

Kind regards, Chris

**Comment by jasonakon** [comment]
Hi @patersonc ,

We're still struggling on getting the recipe to work. We were wondering whether u guys are possible to have time to try out the meta-renesas-ai in V3M ?

**Comment by patersonc** [comment]
Hello @jasonakon,

I've done a quick play and managed to get a build for H3 Salvator-X completed, and tested it on a H3 3.0 4GB Salvator-XS platform.

See my commit 60a9721eb30280fb5a422411409900aa80f5c15a. Simple build instructions are available in https://github.com/patersonc/meta-renesas-ai/blob/rcar-support/meta-tensorflow/templates/salvator-x/build_instructions.md.

Hopefully this helps you.

Regarding V3M, it's not something I've dealt with before, but hopefully what I've done for H3 should be enough to get you on your way.

Kind regards, Chris

**Comment by patersonc** [comment]
I've also added a patch to add tensorflow-lite support now: 60a9721eb30280fb5a422411409900aa80f5c15a
