### ISSUE TITLE
What versions of other Yocto layers are required

### ISSUE THREAD

**Issue by chazste** [renesas-rz/meta-renesas-ai#3]
When building with Yocto layers provided with Renesas 64-bit VLP 1.0.1 Update 1 meta-renesas-ai fails to build. I am trying to build the meta-opencv layer into my image. What "versions" of the other required layers are you building with?

**Comment by patersonc** [comment]
Hello @chazste,

Sorry to hear you're having issues!

I'm using the versions specified in the RZ/G2 BSP: https://github.com/renesas-rz/meta-rzg2/blob/BSP-1.0.1-update1/README.md

Do you have any more details on the problems you're seeing?

Chris

**Comment by patersonc** [comment]
One thing that's slightly different to the readme above, you'll need to include the meta-qt5 layer if adding meta-opencv (or meta-caffe2), even if you're only building with core-image-weston.

I'll work on improving the documentation.

**Comment by chazste** [comment]
I'm using meta-rzg2 directly from github at the requested tag. For the rest of the layers I am still using the ones in the download from the Renesas marketplace. The NOTE I am seeing is the following:

NOTE: preferred version 4.1.1% of opencv not available (for item opencv)
NOTE: versions of opencv available: 3.3+gitAUTOINC+87c27a074d_2a9d1b22ed_a62e20676a_34e4206aef_fccf7cd6a4
NOTE: preferred version 4.1.1% of opencv not available (for item opencv-staticdev)
NOTE: versions of opencv available: 3.3+gitAUTOINC+87c27a074d_2a9d1b22ed_a62e20676a_34e4206aef_fccf7cd6a4
NOTE: preferred version 4.1.1% of opencv not available (for item opencv-dev)
NOTE: versions of opencv available: 3.3+gitAUTOINC+87c27a074d_2a9d1b22ed_a62e20676a_34e4206aef_fccf7cd6a4
NOTE: preferred version 4.1.1% of opencv not available (for item opencv-apps)
NOTE: versions of opencv available: 3.3+gitAUTOINC+87c27a074d_2a9d1b22ed_a62e20676a_34e4206aef_fccf7cd6a4
NOTE: preferred version 4.1.1% of opencv not available (for item opencv-samples)
NOTE: versions of opencv available: 3.3+gitAUTOINC+87c27a074d_2a9d1b22ed_a62e20676a_34e4206aef_fccf7cd6a4
NOTE: preferred version 4.1.1% of opencv not available (for item python3-opencv)
NOTE: versions of opencv available: 3.3+gitAUTOINC+87c27a074d_2a9d1b22ed_a62e20676a_34e4206aef_fccf7cd6a4

So what I am wondering is what do I do to get open-cv 4.1.1 into my build.

Thanks!

**Comment by patersonc** [comment]
Hello @chazste,
Can you share your local.conf and bblayers.conf files/contents?
Thanks, Chris

**Comment by chazste** [comment]
Files attached.


[local.conf.txt](https://github.com/renesas-rz/meta-renesas-ai/files/3804870/local.conf.txt)
[bblayers.conf.txt](https://github.com/renesas-rz/meta-renesas-ai/files/3804871/bblayers.conf.txt)

**Comment by patersonc** [comment]
Thanks for sharing the files. It looks like you're building for a custom board - logicpd-rzg2m. Is this correct?

Have you added support to meta-renesas for this board?
You'll also need to add support to meta-renesas-ai, as some patches/recipes are appended for specific machines.

For example, check `COMPATIBLE_MACHINE` in `meta-opencv/recipes-support/opencv/opencv_4.1.1.bbappend` and other files.

`grep -rns COMPATIBLE_MACHINE | grep hihope-rzg2m` should give you a complete list.

**Comment by chazste** [comment]
Yes I am building for a custom machine. 

My custom layer appends the necessary recipes to allow the standard distribution to build. You are correct about the cause of my issue. For some reason I did not even think to check for COMPATIBLE_MACHINE when I was looking for this issue. I really should have gone back and tried to build for the HiHope board. Sorry.

I'll go ahead and close this issue. Thanks for the help.

**Comment by patersonc** [comment]
No worries @chazste.
Let me know how it goes!

And if you can, please share some details on your platform/project.

Kind regards, Chris
