### ISSUE TITLE
ERROR: pytorch-1.0-r0 do_fetch: Fetcher failure: Fetch command export PSEUDO_DISABLED=1;

### ISSUE THREAD

**Issue by pankajjoshi347** [renesas-rz/meta-renesas-ai#4]
hi,
 i have added meta-pytorch i am getting follwoing error while i am building core-image-minimal for raspberry-64 ERROR: pytorch-1.0-r0 do_fetch: Fetcher failure: Fetch command export PSEUDO_DISABLED=1; export DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/1000/bus"; export SSH_AGENT_PID="2986"; export SSH_AUTH_SOCK="/run/user/1000/keyring/ssh"; export PATH="/home/pankaj/workspace/Yocto/openembedded-core/scripts:/home/pankaj/workspace/Yocto/Build_dir/Raspberry/tmp-glibc/work/cortexa72-oe-linux/pytorch/1.0-r0/recipe-sysroot-native/usr/bin/aarch64-oe-linux:/home/pankaj/workspace/Yocto/Build_dir/Raspberry/tmp-glibc/work/cortexa72-oe-linux/pytorch/1.0-r0/recipe-sysroot/usr/bin/crossscripts:/home/pankaj/workspace/Yocto/Build_dir/Raspberry/tmp-glibc/work/cortexa72-oe-linux/pytorch/1.0-r0/recipe-sysroot-native/usr/sbin:/home/pankaj/workspace/Yocto/Build_dir/Raspberry/tmp-glibc/work/cortexa72-oe-linux/pytorch/1.0-r0/recipe-sysroot-native/usr/bin:/home/pankaj/workspace/Yocto/Build_dir/Raspberry/tmp-glibc/work/cortexa72-oe-linux/pytorch/1.0-r0/recipe-sysroot-native/sbin:/home/pankaj/workspace/Yocto/Build_dir/Raspberry/tmp-glibc/work/cortexa72-oe-linux/pytorch/1.0-r0/recipe-sysroot-native/bin:/home/pankaj/workspace/Yocto/openembedded-core/bitbake/bin:/home/pankaj/workspace/Yocto/Build_dir/Raspberry/tmp-glibc/hosttools"; export HOME="/home/pankaj"; /usr/bin/env wget -t 2 -T 30 --passive-ftp --no-check-certificate -P /home/pankaj/workspace/Yocto/Build_dir/Raspberry/downloads 'https://download.pytorch.org/libtorch/cpu/libtorch-cxx11-abi-shared-with-deps-1.0.zip' --progress=dot -v failed with exit code 8, output:
Loading https://download.pytorch.org/libtorch/cpu/libtorch-cxx11-abi-shared-with-deps-1.0.zip'...
--2021-01-20 16:29:35--  https://download.pytorch.org/libtorch/cpu/libtorch-cxx11-abi-shared-with-deps-1.0.zip
Loading https://download.pytorch.org/libtorch/cpu/libtorch-cxx11-abi-shared-with-deps-1.0.zip...
Resolving download.pytorch.org (download.pytorch.org)... 13.32.33.118, 13.32.33.43, 13.32.33.129, ...
Connecting to download.pytorch.org (download.pytorch.org)|13.32.33.118|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2021-01-20 16:29:36 ERROR 403: Forbidden

can someone suggest me why this could be ???

**Comment by patersonc** [comment]
Hello @pankajjoshi347 ,

Firstly, are you actually using meta-renesas-ai?
Looking at your logs it looks like you're using R-Pi and PyTorch v1.0, neither of which are supported here.

Regardless, looking at the error - can you actually access that link outside of Yocto? I can't; I also get a 403 error.

My guess would be that newer versions of PyTorch have moved to a newer version of that file and the old one is no longer available. You'd have to check with PyTorch.
